spring:
  application:
    name: pprb-api
  datasource:
    url: jdbc:postgresql://ep-crimson-wave-agglnc9y-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_Jo6fK3vBEtYp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect