spring:
  application:
    name: pprb-api
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect